"""Public interface for PDECert."""

from .benchmark import BENCHMARK_VERSION, BenchmarkError, corpus_sha256, evaluate_corpus
from .artifacts import CallableCandidate, SolutionArtifact, SymbolicCandidate
from .autodiff import (
    AutodiffCheckContext,
    AutodiffConstraint,
    AutodiffEvaluation,
    AutodiffProblem,
    AutodiffResidualChecker,
    default_autodiff_checker_registry,
    verify_callable,
)
from .checks import (
    CheckContext,
    CheckerError,
    Checker,
    CheckerRegistry,
    CheckResult,
    default_checker_registry,
    run_checks,
)
from .core import (
    PARAMETER_ASSUMPTIONS,
    Constraint,
    Problem,
    Report,
    Status,
    Witness,
    fixed_collocation_check,
    verify,
    verify_artifact,
)
from .corpus import (
    ANNOTATION_STATUSES,
    CORPUS_VERSION,
    FAILURE_MODES,
    ORIGIN_KINDS,
    VERDICTS,
    CorpusError,
    dump_corpus,
    load_corpus,
    output_sha256,
    validate_corpus,
)
from .labeling import REVIEW_VERSION, ReviewError, apply_review
from .release import RELEASE_VERSION, ReleaseError, build_release_bundle, validate_release_inputs
from .schema import (
    SchemaError,
    VerificationCase,
    case_from_dict,
    case_to_dict,
    dump_case,
    load_case,
)

__all__ = [
    "ANNOTATION_STATUSES",
    "BENCHMARK_VERSION",
    "BenchmarkError",
    "CallableCandidate",
    "CheckContext",
    "CheckResult",
    "Checker",
    "CheckerError",
    "CheckerRegistry",
    "CORPUS_VERSION",
    "Constraint",
    "CorpusError",
    "FAILURE_MODES",
    "ORIGIN_KINDS",
    "PARAMETER_ASSUMPTIONS",
    "Problem",
    "REVIEW_VERSION",
    "RELEASE_VERSION",
    "Report",
    "ReviewError",
    "ReleaseError",
    "SchemaError",
    "Status",
    "SolutionArtifact",
    "SymbolicCandidate",
    "AutodiffCheckContext",
    "AutodiffConstraint",
    "AutodiffEvaluation",
    "AutodiffProblem",
    "AutodiffResidualChecker",
    "VerificationCase",
    "VERDICTS",
    "Witness",
    "case_from_dict",
    "case_to_dict",
    "corpus_sha256",
    "apply_review",
    "build_release_bundle",
    "dump_case",
    "dump_corpus",
    "evaluate_corpus",
    "default_checker_registry",
    "default_autodiff_checker_registry",
    "fixed_collocation_check",
    "load_case",
    "load_corpus",
    "output_sha256",
    "run_checks",
    "validate_corpus",
    "validate_release_inputs",
    "verify",
    "verify_artifact",
    "verify_callable",
]

__version__ = "0.1.0"
